local size = 720 / 1080
local t = Def.ActorFrame{
	LoadActor("opening")..{
		InitCommand=cmd(Center;zoom,size);
		OnCommand=cmd(diffusealpha,1;sleep,11/6;diffusealpha,0;)
	};
	LoadActor("Transition")..{
		InitCommand=cmd(Center;zoom,size);
		OnCommand=cmd(cropleft,1;sleep,2;linear,1/4;cropleft,0);
	};
	LoadActor("crystal")..{
		InitCommand=cmd(Center;zoom,size);
		OnCommand=cmd(diffusealpha,0;sleep,166/60;linear,1/3;diffusealpha,1);
	};
	Def.ActorFrame{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38;zoom,0.5;rotationz,-12.22);
		-- First cycle
		LoadActor("flare")..{
			InitCommand=cmd(x,0;y,-120;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,3;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,540;diffusealpha,0.8;linear,0.2;addx,540;diffusealpha,0;sleep,3;addx,-1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-1080;y,-180;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,3;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,540;diffusealpha,0.8;linear,0.2;addx,540;diffusealpha,0;sleep,3;addx,-1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-420;y,-280;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,3;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,540;diffusealpha,0.8;linear,0.2;addx,540;diffusealpha,0;sleep,3;addx,-1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-320;y,280;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,3;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,-540;diffusealpha,0.8;linear,0.2;addx,-540;diffusealpha,0;sleep,3;addx,1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,1280;y,440;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,3;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,-540;diffusealpha,0.8;linear,0.2;addx,-540;diffusealpha,0;sleep,3;addx,1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,0;y,480;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,3;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,-540;diffusealpha,0.8;linear,0.2;addx,-540;diffusealpha,0;sleep,3;addx,1080;queuecommand,"Loop");
		};
		-- Second cycle
		LoadActor("flare")..{
			InitCommand=cmd(x,0;y,-480;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,4.5;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,-540;diffusealpha,0.8;linear,0.2;addx,-540;diffusealpha,0;sleep,3;addx,1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-1080;y,-560;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,4.5;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,-540;diffusealpha,0.8;linear,0.2;addx,-540;diffusealpha,0;sleep,3;addx,1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-420;y,-420;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,4.5;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,-540;diffusealpha,0.8;linear,0.2;addx,-540;diffusealpha,0;sleep,3;addx,1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-320;y,660;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,4.5;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,540;diffusealpha,0.8;linear,0.2;addx,540;diffusealpha,0;sleep,3;addx,-1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,1280;y,740;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,4.5;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,540;diffusealpha,0.8;linear,0.2;addx,540;diffusealpha,0;sleep,3;addx,-1080;queuecommand,"Loop");
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,0;y,820;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,4.5;queuecommand,"Loop");
			LoopCommand=cmd(linear,0.2;addx,540;diffusealpha,0.8;linear,0.2;addx,540;diffusealpha,0;sleep,3;addx,-1080;queuecommand,"Loop");
		};
	};
};
return t;