local t = Def.ActorFrame{
	LoadActor("up")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38;zoom,0.5);
		OnCommand=cmd(addx,-128;addy,30;cropleft,1;sleep,2;linear,1/4;cropleft,0;sleep,1/3;accelerate,1/6;addx,128;addy,-30;pause;diffusealpha,0);
	};
	LoadActor("down")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38;zoom,0.5);
		OnCommand=cmd(addx,128;addy,-30;cropright,1;sleep,2;linear,1/4;cropright,0;sleep,1/3;accelerate,1/6;addx,-128;addy,30;sleep,1/60;diffusealpha,0);
	};
	LoadActor("PendulaLogo")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38);
		OnCommand=cmd(diffusealpha,0;zoom,0.5;sleep,166/60;diffusealpha,1);
	};
	LoadActor("PendulaLogo")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38;blend,'BlendMode_Add');
		OnCommand=cmd(diffusealpha,0;sleep,166/60;queuecommand,"Loop");
		LoopCommand=cmd(zoom,0.5;diffusealpha,0.5;linear,1;zoom,0.51;diffusealpha,0;sleep,1;queuecommand,"Loop")
	};
	LoadActor("white")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38);
		OnCommand=cmd(diffusealpha,0;zoom,0.5;sleep,166/60;diffusealpha,1;smooth,0.5;diffusealpha,0);
	};
	Def.ActorFrame{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38;zoom,0.5;rotationz,-12.22);
		LoadActor("trace")..{
			InitCommand=cmd(x,2400;y,-240;blend,'BlendMode_Add');
			OnCommand=cmd(sleep,2;linear,1/4;x,-2400);
		};
		LoadActor("trace")..{
			InitCommand=cmd(rotationz,180;x,-2400;y,320;blend,'BlendMode_Add');
			OnCommand=cmd(sleep,2;linear,1/4;x,2400);
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,240;y,-60;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,2;linear,0.2;addx,-180;diffusealpha,1;linear,0.2;addx,-180;diffusealpha,0;);
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-340;y,-160;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,2.1;linear,0.2;addx,-180;diffusealpha,1;linear,0.2;addx,-180;diffusealpha,0;);
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,240;y,60;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,2;linear,0.2;addx,180;diffusealpha,1;linear,0.2;addx,180;diffusealpha,0;);
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-60;y,80;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,2.04;linear,0.2;addx,180;diffusealpha,1;linear,0.2;addx,180;diffusealpha,0;);
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,240;y,260;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,2.1;linear,0.2;addx,180;diffusealpha,1;linear,0.2;addx,180;diffusealpha,0;);
		};
		LoadActor("flare")..{
			InitCommand=cmd(x,-240;y,140;blend,'BlendMode_Add');
			OnCommand=cmd(diffusealpha,0;sleep,2.06;linear,0.2;addx,180;diffusealpha,1;linear,0.2;addx,180;diffusealpha,0;);
		};
		LoadActor("fuse")..{
			InitCommand=cmd(x,-1920;y,0;blend,'BlendMode_Add');
			OnCommand=cmd(sleep,2.5;linear,3/12;addx,2640;diffusealpha,1;linear,0.2;diffusealpha,0;);
		};
	};
	LoadActor("middleflare")..{
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-38;blend,'BlendMode_Add');
		OnCommand=cmd(diffusealpha,0;zoom,0.5;sleep,4;queuecommand,"Loop");
		LoopCommand=cmd(linear,8;diffusealpha,1;linear,8;diffusealpha,0;queuecommand,"Loop");
	};
};
return t;